export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';

export const ACTION_MODEL = 'ACTION_MODEL';
export const ORDER_MODEL = 'ORDER_MODEL';
export const PROCESSING_RULE_MODEL = 'PROCESSING_RULE_MODEL';
